### ISSUE TITLE
Exported JSON throws an error if npc statblock contains a spell generated by the new compendium function

### ISSUE THREAD

**Issue by gesalt** [xeqi/fu-parser#3]
Spells added to NPC sheets using the NPC compendium feature added to Fultimator cause exported code to throw an error.
![cebs4H0 1](https://github.com/user-attachments/assets/cd62c907-121d-4a36-9238-45a6373ddf83)

This is because spells (and potentially other things) added through that function do not have a range parameter. Manually added spells still have a range parameter.

**Comment by spyrella** [comment]
This has been resolved in Release 0.0.8
